
server:
  port: 8080
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie     
    context-path: /
    encoding:
      charset: utf-8

# hibernate는 SQL을 직접 사용하지 않고 메서드만으로 쿼리를 사용해주게 하는 라이브러리
# hibernate 기술을 쉽게 사용하게 해주는 라이브러리가 JPA이다.
# ddl-auto : create는 서버 실행할 때마다 테이블을 삭제하고 새로 만드는 설정이다.
# ddl-auto : none는 서버 실행할 때마다 아무것도 하지 않는 옵션이다.
# ddl-auto : update는 필드 수정시에 필요한 옵션이다.
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 아이디
    password: 비번
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  mustache:
    expose-session-attributes: true
  datasource:

      url: jdbc:mariadb://localhost:3306/greendb2

      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: green1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sq: true

  output:
    ansi:
      enabled: always
